{% set name = "django-socio-grpc" %}
{% set version = "0.24.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/django_socio_grpc-{{ version }}.tar.gz
  sha256: a4dfb417866b17ab1ae49a32b0c6eb540c006e488c4b687530dc5e9b18690214

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - lark >=1.0.0,<2.0.0
    - python >=3.8,<4.0
    - django >=4.2
    - djangorestframework
    - grpcio-tools >=1.50.0,<2.0.0
    - lark-parser >=0.12.0,<0.13.0
    - grpcio-health-checking

test:
  imports:
    - django_socio_grpc
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Fork of django-grpc-framework with more feature maintained by the socio team. Make GRPC with django easy.
  home: https://github.com/socotecio/django-socio-grpc
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
