{% set name = "django-socio-grpc" %}
{% set version = "0.20.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django_socio_grpc-{{ version }}.tar.gz
  sha256: af42a7a73c427746ab009ec796453cfa3630850c2d162ddfdec53c74d60221a0

build:
  noarch: python
  entry_points:
    - tests = "test_utils.load_tests:launch"
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8
    - django >=4.2
    - djangorestframework >=3.14.0
    - grpcio >=1.50.0,<2.0.0
    - grpcio-tools >=1.50.0,<2.0.0
    - proto-parser >=1.6.3,<2.0.0

test:
  imports:
    - django_socio_grpc

about:
  summary: Fork of django-grpc-framework with more feature maintained by the socio team. Make GRPC with django easy.
  home: https://github.com/socotecio/django-socio-grpc
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
